import { Cabin } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/NavBar";
import Footer from "@/components/layout/Footer";

const cabin = Cabin({
  variable: "--font-cabin",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${cabin.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <NavBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
